#!/usr/bin/env bash
# Bash script to display "Best School" 10 times 

counter=0

while [ $counter -lt 10 ]; do
if [ $counter -eq 8 ]; then
echo -e "Best School\nHi"
else
echo "Best School"
fi
    
((counter++))
done
